<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Projects</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            text-align: center;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        h1 {
            margin-top: 20px;
        }
        #projects {
            display: flex;
            flex-wrap: wrap;
            justify-content: center;
            margin-top: 20px;
        }
        .project-card {
            background: white;
            border-radius: 8px;
            padding: 15px;
            margin: 10px;
            width: 300px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.2);
            text-align: left;
        }
        .project-card a {
            text-decoration: none;
            color: #0366d6;
            font-weight: bold;
        }
    </style>
</head>
<body>

    <h1>My GitHub Projects</h1>
    <p>Fetching public repositories from my GitHub...</p>

    <div id="projects"></div>

    <script>
        const username = "your-github-username"; // Replace with your GitHub username
        const apiUrl = `https://api.github.com/users/${username}/repos`;

        async function fetchProjects() {
            try {
                const response = await fetch(apiUrl);
                const repositories = await response.json();

                const projectsContainer = document.getElementById("projects");
                projectsContainer.innerHTML = ""; // Clear previous content

                repositories.forEach(repo => {
                    const projectCard = document.createElement("div");
                    projectCard.classList.add("project-card");

                    projectCard.innerHTML = `
                        <h3><a href="${repo.html_url}" target="_blank">${repo.name}</a></h3>
                        <p>${repo.description || "No description available."}</p>
                        <p>⭐ ${repo.stargazers_count} | 🍴 ${repo.forks_count}</p>
                    `;

                    projectsContainer.appendChild(projectCard);
                });
            } catch (error) {
                console.error("Error fetching GitHub repos:", error);
            }
        }

        fetchProjects();
    </script>

</body>
</html>
